.idea/gradle.xml
.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/banchan/BanChanApp.kt
app/src/main/java/com/example/banchan/MainActivity.kt
app/src/main/java/com/example/banchan/data/response/best/BestResponse.kt
app/src/main/java/com/example/banchan/data/response/best/Body.kt
app/src/main/java/com/example/banchan/data/response/best/Item.kt
app/src/main/java/com/example/banchan/data/response/detail/Data.kt
app/src/main/java/com/example/banchan/data/response/detail/DetailResponse.kt
app/src/main/java/com/example/banchan/data/response/main/MainResponse.kt
app/src/main/java/com/example/banchan/data/response/side/SideResponse.kt
app/src/main/java/com/example/banchan/data/response/soup/SoupResponse.kt
app/src/main/java/com/example/banchan/di/NetworkModules.kt
app/src/main/java/com/example/banchan/remote/BanChanApi.kt

네트워크 모듈 구현, api 추가
- 네트워크 모듈 구현
- 필요 api 추가
- 응답 data class 추가 (코틀린 컨벤션 맞춤)
- 요청 테스트 완료
Closes #5

[FEAT] 네트워크 모듈 구현, api 추가

---

app/src/main/java/com/example/banchan/MockData.kt
app/src/main/java/com/example/banchan/data/api/BanChanApi.kt
app/src/main/java/com/example/banchan/data/repository/BanChanRepository.kt
app/src/main/java/com/example/banchan/data/repository/BanChanRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/response/best/Body.kt
app/src/main/java/com/example/banchan/data/response/best/Item.kt
app/src/main/java/com/example/banchan/data/source/remote/BanChanDataSource.kt
app/src/main/java/com/example/banchan/data/source/remote/BanChanRemoteDataSource.kt
app/src/main/java/com/example/banchan/di/CoroutinesModule.kt
app/src/main/java/com/example/banchan/di/DataSourceModule.kt
app/src/main/java/com/example/banchan/di/NetworkModules.kt
app/src/main/java/com/example/banchan/di/RepositoryModule.kt
app/src/main/java/com/example/banchan/domain/model/BestListItem.kt
app/src/main/java/com/example/banchan/domain/model/BestModel.kt
app/src/main/java/com/example/banchan/domain/model/ItemModel.kt
app/src/main/java/com/example/banchan/domain/repository/BanChanRepository.kt
app/src/main/java/com/example/banchan/domain/usecase/GetBestDishesUseCase.kt
app/src/main/java/com/example/banchan/presentation/adapter/best/BestListAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/home/HomeViewPagerAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/menu/MenuAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/menu/MenuViewHolder.kt
app/src/main/java/com/example/banchan/presentation/custom/OrderingAppBar.kt
app/src/main/java/com/example/banchan/presentation/home/HomeFragment.kt
app/src/main/java/com/example/banchan/util/ext/OrderingAppBarBindingAdapter.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/item_menu.xml

- Remote DataSoruce, Repository를 구현합니다.
- Best Dishe의 Usecase를 구현합니다. (나머지 usecase는 추후 구현 예정)
- 패키지를 클린 아키텍처에 맞춰 분리합니다.
Closes #13

[FEAT] Banchan Remote DataSoruce, Repository 구현

---

.idea/misc.xml
app/src/main/java/com/example/banchan/domain/model/ItemModel.kt
app/src/main/java/com/example/banchan/presentation/custom/FilterAdapter.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/adapter/MainAdapter.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/adapter/MainFilterViewHolder.kt
app/src/main/java/com/example/banchan/util/ext/StrExt.kt
app/src/main/res/layout/item_menu_filter.xml
app/src/main/res/layout/menu_filter.xml
app/src/main/res/values/array.xml

스피너 구현, 메인 필터링 기능 구현
- 스피너 구현
- 메인 필터링 기능 구현
Closes #16

[FEAT] 스피너 구현, 메인 필터링 기능 구현 #16

---

.idea/misc.xml
app/src/main/java/com/example/banchan/data/response/soup/SoupResponse.kt
app/src/main/java/com/example/banchan/domain/usecase/GetSoupDishesUseCase.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/soup/adapter/SoupAdapter.kt
app/src/main/java/com/example/banchan/presentation/home/soup/adapter/TotalFilterViewViewHolder.kt
app/src/main/res/layout/fragment_soup.xml
app/src/main/res/layout/total_filter.xml
app/src/main/res/values/strings.xml

국물 요리 화면 UI, 로직 구현
- 국물 요리 화면 UI, 로직 구현
Closes #20

[FEAT] 국물 요리 화면 UI, 로직 구현 #20 

---

.idea/misc.xml
app/src/main/java/com/example/banchan/data/response/side/SideResponse.kt
app/src/main/java/com/example/banchan/domain/model/ItemModel.kt
app/src/main/java/com/example/banchan/domain/usecase/GetSideDishesUseCase.kt
app/src/main/java/com/example/banchan/presentation/adapter/home/CommonAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/home/CommonFilterViewViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/LargeMenuViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/MainAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/MainFilterViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/MediumMenuViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/SpacingItemDecorator.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
app/src/main/res/layout/fragment_side.xml

밑반찬 화면 UI, 로직 구현
- 밑반찬 화면 UI, 로직 구현
- 패키지 수정
Closes #22

[FEAT] 밑반찬 화면 UI, 로직 구현 #22

---

app/src/main/java/com/example/banchan/presentation/custom/AmountCounter.kt
app/src/main/java/com/example/banchan/util/ext/AmountCounterBindingAdapter.kt
app/src/main/res/drawable/ic_minus.xml
app/src/main/res/drawable/ic_plus.xml
app/src/main/res/layout/amount_counter.xml
app/src/main/res/values/attrs.xml

- 여러 화면에서 사용되는 수량 카운트를 CustomView로 생성합니다.
Closes #28

[FEAT] 수량 카운트 CustomView

---

app/src/main/java/com/example/banchan/data/Converter.kt
app/src/main/java/com/example/banchan/data/repository/BanChanRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/repository/BasketRepository.kt
app/src/main/java/com/example/banchan/data/repository/BasketRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepository.kt
app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/source/BasketDataSource.kt
app/src/main/java/com/example/banchan/data/source/RecentlyProductDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/BanChanDatabase.kt
app/src/main/java/com/example/banchan/data/source/local/basket/BasketDao.kt
app/src/main/java/com/example/banchan/data/source/local/basket/BasketItem.kt
app/src/main/java/com/example/banchan/data/source/local/basket/BasketLocalDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProduct.kt
app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductDao.kt
app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductLocalDataSource.kt
app/src/main/java/com/example/banchan/di/DataSourceModule.kt
app/src/main/java/com/example/banchan/di/DatabaseModule.kt
app/src/main/java/com/example/banchan/di/RepositoryModule.kt

최근 상품 DB 구현, datasource, repository 구현
- 최근 상품 DB 구현, 쿼리 추가
- 최근 상품 데이터소스, 리포지토리 구현
- 삽입, 조회, 업데이트 쿼리 테스트 완료
Closes #35

[FEAT] 최근 상품 DB 구현, datasource, repository 구현 #35

---

app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryItem.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt

내역 쿼리 수정
- 내역 쿼리 수정
Closes #42

[FEAT] 내역 쿼리 수정 #42

---

app/src/main/java/com/example/banchan/data/response/best/Item.kt
app/src/main/java/com/example/banchan/data/response/detail/DetailResponse.kt
app/src/main/java/com/example/banchan/data/source/remote/BanChanRemoteDataSource.kt
app/src/main/java/com/example/banchan/domain/model/ProductDetailModel.kt
app/src/main/java/com/example/banchan/domain/model/ResponseState.kt
app/src/main/java/com/example/banchan/domain/usecase/GetProductDetailUseCase.kt
app/src/main/java/com/example/banchan/presentation/adapter/best/BestListAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/home/CommonAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/LargeMenuViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/MainAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/main/MediumMenuViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/menu/MenuAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/menu/MenuViewHolder.kt
app/src/main/java/com/example/banchan/presentation/base/BaseFragment.kt
app/src/main/java/com/example/banchan/presentation/home/HomeTabFragment.kt
app/src/main/java/com/example/banchan/presentation/home/best/BestFragment.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
app/src/main/java/com/example/banchan/presentation/main/MainViewModel.kt
app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailViewModel.kt
app/src/main/java/com/example/banchan/util/calcul/DiscountPercentCalcul.kt
app/src/main/java/com/example/banchan/util/ext/StrExt.kt
app/src/main/res/drawable/product_detail_tab_selector.xml
app/src/main/res/drawable/product_thumbnail_selected_dot.xml
app/src/main/res/drawable/product_thumbnail_unselected_dot.xml

- 상품 상세 화면 이동 로직을 작성합니다.
Closes #31

[FEAT] 홈화면 상품 클릭시 상세 화면 로직

---

app/src/main/java/com/example/banchan/presentation/home/best/BestFragment.kt
app/src/main/java/com/example/banchan/presentation/home/best/BestViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookFragment.kt
app/src/main/java/com/example/banchan/presentation/home/maincook/MainCookViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt

- Home 화면의 기획전 외 탭 프래그먼트의 isCartAdded를 체크하는 부분을 개선합니다.
Closes #48

[REFACTOR] 홈화면의 탭 프래그먼트 isCartAdded 체크 로직 개선

---

.idea/misc.xml
app/build.gradle
app/src/main/java/com/example/banchan/domain/usecase/SaveRecentProduct.kt
app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailViewModel.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
app/src/main/res/layout/fragment_recently_product.xml
app/src/main/res/layout/item_recent.xml

최근 본 상품 목록 저장 부분 리팩토링
-  최근 본 상품 목록 저장 부분 리팩토링
디테일 정보를 성공적으로 불러왔을때 한번만 저장하도록 리팩토링
Closes #53

[REFACTOR] 최근 본 상품 목록 저장 부분 리팩토링 #53

---

app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt

flow distinct 적용하도록 수정
- flow distinct 적용하도록 수정
Closes #72

[FIX] flow distinct 적용하도록 수정

---

app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/history/History.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
app/src/main/java/com/example/banchan/domain/usecase/history/InsertHistoryItemsUseCase.kt
app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketOrderAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/basket/BasketOrderViewHolder.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt
app/src/main/res/layout/item_basket_order.xml

- 장바구니 주문 기능을 구현합니다.
- History Table에 배송료 column 추가
- 10000원 이상일시 주문 버튼 활성화
- 주문 완료시 장바구니에서 상품 삭제 및 주문 내역 DB에 추가
Closes #74

[FEAT] 장바구니 주문 기능 구현

---

app/src/main/java/com/example/banchan/OrderService.kt
app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
app/src/main/java/com/example/banchan/domain/usecase/history/GetHistoryByIdUseCase.kt
app/src/main/java/com/example/banchan/domain/usecase/history/InsertHistoryItemsUseCase.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketViewModel.kt
app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt

주문 완료 누르면 주문 상태 화면으로 이동
- 주문 완료 누르면 주문 상태 화면으로 이동
Closes #81

[FEAT] 주문 완료 누르면 주문 상태 화면으로 이동 #81 

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt
app/src/main/res/values/splash.xml

[FEAT] 스플래시 화면 구현

---

app/src/main/java/com/example/banchan/presentation/UiState.kt

- Init, Loading, Success, Error, Empty로 UiState를 구분할 수 있는 Sealed Class를 생성합니다.
- 페어 프로그래밍으로 진행하였습니다.
Closes #102

[REFACTOR] UiState Class 생성

---

app/src/main/java/com/example/banchan/presentation/adapter/common/CommonAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/common/CommonFilterAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/home/HomeHeaderAdapter.kt
app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideViewModel.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupViewModel.kt
app/src/main/res/layout/fragment_side.xml
app/src/main/res/layout/fragment_soup.xml

국물, 밑반찬 요리 리팩토링(ConcatAdapter 사용, UiState 관리, 리로드 구현)
- 국물 요리 ConcatAdapter 사용, UiState 관리, 리로드 구현
- 밑반찬 요리 ConcatAdapter 사용, UiState 관리, 리로드 구현
Closes #106

[REFACTOR] 국물, 밑반찬 요리 리팩토링(ConcatAdapter 사용, UiState 관리, 리로드 구현) #106

---

.idea/misc.xml
app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderFooterAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderFooterViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderHeaderAdapter.kt
app/src/main/java/com/example/banchan/presentation/adapter/common/CommonOrderHeaderViewHolder.kt
app/src/main/java/com/example/banchan/presentation/adapter/ordersuccess/OrderSuccessItemAdapter.kt
app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessViewModel.kt
app/src/main/res/layout/fragment_order_success.xml
app/src/main/res/layout/item_order_header.xml

주문 상태 화면 UiState 관리
- 주문 상태 화면 UiState 관리
Closes #119

[REFACTOR] 주문 상태 화면 UiState 관리 #119 

---

app/src/main/java/com/example/banchan/AlarmReceiver.kt
app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt

내용을 적어주세요
- 내용을 적어주세요
Closes #이슈번호

[FEAT] notification 누르면 OrderSuccess 화면으로 이동하도록 구현 #111

---

.idea/misc.xml
app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
app/src/main/res/layout/fragment_recently_product.xml

최근 본 상품 UiState 관리
- 최근 본 상품 UiState 관리
uiState databinding 적용 pr 머지 후 empty, error, progress 바인딩 예정
Closes #123

[REFACTOR] 최근 본 상품 UiState 관리 #123

---

.idea/misc.xml
app/build.gradle
app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepository.kt
app/src/main/java/com/example/banchan/data/repository/RecentlyProductRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/source/RecentlyProductDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductDao.kt
app/src/main/java/com/example/banchan/data/source/local/recent/RecentlyProductLocalDataSource.kt
app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductPagingUseCase.kt
app/src/main/java/com/example/banchan/domain/usecase/recently/GetRecentProductUseCase.kt
app/src/main/java/com/example/banchan/presentation/adapter/recentlyproduct/RecentlyProductPagingAdapter.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketListViewModel.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketRecentlyProductViewModel.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductViewModel.kt
app/src/main/java/com/example/banchan/util/ext/BindingAdapters.kt
app/src/main/res/layout/fragment_recently_product.xml
app/src/main/res/layout/layout_recent_empty.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/example/banchan/data/RecentProductFakeDataSource.kt

최근 본 상품 화면 페이징 적용
- 최근 본 상품 화면 페이징 적용
Closes #132

[FEAT] 최근 본 상품 화면 페이징 적용 #132

---

app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
app/src/main/java/com/example/banchan/presentation/home/best/BestFragment.kt
app/src/main/java/com/example/banchan/presentation/home/maindish/MainDishFragment.kt
app/src/main/java/com/example/banchan/presentation/home/side/SideFragment.kt
app/src/main/java/com/example/banchan/presentation/home/soup/SoupFragment.kt
app/src/main/java/com/example/banchan/presentation/orderlist/OrderListFragment.kt
app/src/main/java/com/example/banchan/presentation/ordersuccess/OrderSuccessFragment.kt
app/src/main/java/com/example/banchan/presentation/productdetail/ProductDetailFragment.kt
app/src/main/java/com/example/banchan/presentation/recentlyproduct/RecentlyProductFragment.kt

어댑터 lateinit으로 수정
- 어댑터 lateinit으로 수정
Closes #135

[FIX] 어댑터 lateinit으로 수정 #135

---

app/src/main/res/layout/item_order_footer.xml

배송 상태 화면 바텀 padding 추가
- 배송 상태 화면 바텀 padding 추가
Closes #145

[FIX] 배송 상태 화면 바텀 padding 추가 #145

---

app/src/main/res/drawable/spinner_arrow.xml
app/src/main/res/drawable/spinner_check.xml
app/src/main/res/drawable/spinner_close.xml
app/src/main/res/drawable/spinner_open.xml
app/src/main/res/layout/menu_filter.xml

spinner 오른쪽 맞춤, ui 세로 방향 center 맞춤
- spinner 오른쪽 맞춤
- ui 세로 방향 center 맞춤
**변경전**
- 스피너 화살표가 오른쪽에 맞춰져있지 x
- ui 세로 방향 center가 맞지 않음
**변경후**
Closes #152

[FIX] spinner 오른쪽 맞춤, ui 세로 방향 center 맞춤 #152

---

app/src/main/java/com/example/banchan/presentation/main/MainActivity.kt

중복 주문 상태 프래그먼트 pop
- 중복 주문 상태 프래그먼트 pop
Closes #144

[FIX] 중복 주문 상태 프래그먼트 pop #144 

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/banchan/AlarmReceiver.kt
app/src/main/java/com/example/banchan/BootAlarmReceiver.kt
app/src/main/java/com/example/banchan/HistoryAlarmWorker.kt
app/src/main/java/com/example/banchan/OrderSuccessWorker.kt
app/src/main/java/com/example/banchan/data/repository/HistoryRepository.kt
app/src/main/java/com/example/banchan/data/repository/HistoryRepositoryImpl.kt
app/src/main/java/com/example/banchan/data/source/HistoryDataSource.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryDao.kt
app/src/main/java/com/example/banchan/data/source/local/history/HistoryLocalDataSource.kt
app/src/main/java/com/example/banchan/domain/usecase/history/GetHistoryStreamUseCase.kt
app/src/main/java/com/example/banchan/presentation/basket/BasketFragment.kt
app/src/main/java/com/example/banchan/presentation/home/OrderStateViewModel.kt
app/src/main/java/com/example/banchan/util/AlarmUtil.kt
app/src/main/java/com/example/banchan/util/Constant.kt

기기 재부팅 후에도 배송 알림 제공되도록 수정
**기기 reboot시 alarm clear됨**
- reboot시 필요한 알람 재등록하여 배송 알림 제공되도록 수정
Closes #141

[FIX] 기기 재부팅 후에도 배송 알림 제공되도록 수정 #141

---

.idea/misc.xml
app/src/main/res/layout/appbar_ordering.xml

- appBar 버튼이 클릭 안되는 현상을 개선합니다.
Closes #143

[FIX] #143 - 앱바의 메뉴 잘 눌리도록 개선 진행
